"""Generate train-only EDA and publish measured run outputs in the README."""

import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from src.features.build_features import FEATURES
from src.models.common import read_dataset
from src.utils.config import ROOT, get_path, load_config
from src.utils.provenance import write_json


def eda(cfg: dict) -> dict:
    df, manifest = read_dataset(cfg)
    training = df.loc[df.split == "train"].copy()
    folder = get_path(cfg, "artifacts") / "eda"
    folder.mkdir(parents=True, exist_ok=True)
    training[FEATURES + ["target"]].describe().to_csv(folder / "descriptive_statistics.csv")
    training.isna().sum().to_csv(folder / "missing_values.csv")
    columns = ["temperature", "precipitation", "humidity", "et0", "rainfall_30d", "target"]
    fig, axes = plt.subplots(2, 3, figsize=(12, 7))
    for column, ax in zip(columns, axes.flat, strict=True):
        ax.hist(training[column], bins=35, color="#277c8e")
        ax.set(title=column, ylabel="Training observations")
    fig.suptitle("Training data only: distributions")
    fig.tight_layout()
    fig.savefig(folder / "distributions.png", dpi=140)
    plt.close(fig)
    correlations = training[FEATURES + ["target"]].corr()
    correlations.to_csv(folder / "correlations.csv")
    fig, ax = plt.subplots(figsize=(12, 10))
    sns.heatmap(correlations, cmap="RdBu_r", center=0, vmin=-1, vmax=1, ax=ax)
    ax.set_title("Training Pearson correlations; constant columns have undefined correlation")
    fig.tight_layout()
    fig.savefig(folder / "correlation.png", dpi=140)
    plt.close(fig)
    fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    for (site, group), ax in zip(training.groupby("site_id"), axes, strict=True):
        # Reindex to daily dates so off-season gaps are not connected by lines.
        series = group.set_index("target_date").target.asfreq("D")
        ax.plot(series.index, series, color="#277c8e", linewidth=0.8)
        ax.set(ylabel="Stress proxy", title=site, ylim=(0, 1))
    fig.suptitle("Training growing seasons: modeled target through time")
    fig.tight_layout()
    fig.savefig(folder / "time_series.png", dpi=140)
    plt.close(fig)
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    for column, ax in zip(["rainfall_30d", "et0", "temperature"], axes, strict=True):
        ax.scatter(training[column], training.target, s=8, alpha=0.2, color="#277c8e")
        ax.set(xlabel=column, ylabel="Tomorrow's stress proxy")
    fig.tight_layout()
    fig.savefig(folder / "relationships.png", dpi=140)
    plt.close(fig)
    q1, q3 = training[columns].quantile(0.25), training[columns].quantile(0.75)
    iqr = q3 - q1
    flagged = ((training[columns] < q1 - 1.5 * iqr) | (training[columns] > q3 + 1.5 * iqr)).sum()
    flagged.to_csv(folder / "iqr_outliers.csv")
    summary = {
        "dataset_rows": manifest["rows"],
        "training_rows": len(training),
        "training_target_zero_fraction": float(training.target.eq(0).mean()),
        "training_target_mean": float(training.target.mean()),
        "outlier_counts": flagged.to_dict(),
        "policy": "IQR flags are descriptive only. Valid extremes are retained. "
        "No validation/test outcome plots are used in exploration.",
    }
    write_json(folder / "summary.json", summary)
    return summary


def publish_results(cfg: dict):
    folder = get_path(cfg, "artifacts")
    pointer = json.loads((get_path(cfg, "models") / "candidate.json").read_text())
    result = json.loads(
        (folder / "evaluation" / pointer["model_version"] / "test_metrics.json").read_text()
    )
    comparison = pd.read_csv(folder / "model_comparison.csv")
    lines = [
        "Results below are generated by `python -m src.reports` from pipeline artifacts.",
        "",
        "| Model | Validation MAE | Validation RMSE | Validation R² |",
        "|---|---:|---:|---:|",
    ]
    for row in comparison.itertuples():
        lines.append(f"| {row.model} | {row.mae:.4f} | {row.rmse:.4f} | {row.r2:.4f} |")
    lines.extend(
        [
            "",
            f"Selected **{result['model_type']}**, version `{result['model_version']}`.",
            f"Held-out test: **{result['test_rows']} observations**.",
            "",
            "| Frozen test comparison | MAE | RMSE | R² |",
            "|---|---:|---:|---:|",
        ]
    )
    for label, scores in [
        ("Selected ML model", result["metrics"]),
        ("Stateful persistence comparator", result["persistence_metrics"]),
    ]:
        lines.append(
            f"| {label} | {scores['mae']:.4f} | {scores['rmse']:.4f} | {scores['r2']:.4f} |"
        )
    lines.extend(
        [
            "",
            "These measure agreement with the modeled proxy, **not measured crop stress**.",
            "Persistence has access to today's full-history simulated state; the ML model",
            "uses 30 days of weather and static scenario soil parameters. This information",
            "advantage must be considered when interpreting the comparison.",
            "",
            "![Validation comparison](artifacts/model_comparison.png)",
        ]
    )
    text = "\n".join(lines)
    (folder / "results.md").write_text(text + "\n")
    readme = ROOT / "README.md"
    before, after = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"
    content = readme.read_text()
    if before in content and after in content:
        content = (
            content.split(before)[0] + before + "\n" + text + "\n" + after + content.split(after)[1]
        )
        readme.write_text(content)


if __name__ == "__main__":
    config = load_config()
    eda(config)
    publish_results(config)
